### ISSUE TITLE
Downloading the created clang-format does not contain all selected options

### ISSUE THREAD

**Issue by chill-nemesis** [Wirena/clang-format-configurator-v2#21]
# Info
Configurator was set to `16.0.1`
Browser is Vivaldi 6.0.2979.18 stable

# Issue
After modifying some of the options and downloading the .clang-format file, some of the options are missing.

I first assumed that it were only some default values, but after comparing against the default clang-format documentation, that does not seem to be the case.
It seems to be always the same options that are missing though.
One example for me was `AlignOperands: Align` which I set but was missing in the downloaded file.

I have attached a section of my desired config as it is set in your configurator: 
![image](https://github.com/Wirena/clang-format-configurator-v2/assets/12547922/6ddcb22d-f4d2-44d5-96db-21248772f02f)

and here is the corresponding section from the generated clang-format file:
```
BraceWrapping:
  AfterClass: false
  BeforeLambdaBody: true
  IndentBraces: false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false
```

**Comment by Wirena** [comment]
@chill-nemesis Did you use Upload function to load existing config before modifying these options? Can you send me whole generated clang-format file?

**Comment by chill-nemesis** [comment]
I created the file from scratch. The preview is fine, only the downloaded version is faulty.

I have attached the [faulty version](https://github.com/Wirena/clang-format-configurator-v2/files/11474814/clang-format_downloaded.txt)  and a [manually fixed version](https://github.com/Wirena/clang-format-configurator-v2/files/11474833/clang-format_fixed.txt). Note that at some point I did not bother updating missing configs for non-c++ settings as well as the penalty-terms (I did not change them from the default values I think).

**Comment by Wirena** [comment]
@chill-nemesis yep, can confirm. During file generation options which values match BasedOnStyle values are omitted, because that's how I thought it works on clang-format side, i.e. if BasedOnStyle is set to GNU, then all non mentioned options fall back to GNU style. In your case, `AlignOperands` is set to `Align` both in GNU and in configurator, that's why it was not present in the faulty file, but apparently it does not work this way. 
I'll fix that, thanks

**Comment by Wirena** [comment]
@chill-nemesis Should be fixed, i checked by uploading your fixed config, downloading configurator generated config and formatting file locally using this generated file, the results are identical to when using your fixed config, but it would be nice if you can double check it.

Now I have to insert all options, but it's better then invalid result

**Comment by chill-nemesis** [comment]
I uploaded my configuration (which was missing a couple of options, mostly not related to c++ settings) and re-downloaded it. The downloaded file seems to be complete (at least all of my options were still the same) and the few missing non-c++ options are also there ;).
Thank you @Wirena for fixing the issue!

As a side-note/possible additional feature: Consider keeping comments in the uploaded file (maybe you can tag that to the next clang-format option in the file?)
I have the following comment in my format:
```
# Setting the string-break penalty low enables us to rather break a string than to move it to a new line
# this is especially useful for something like this: throw error("a VeryVeryVeryLongString")
# With a high string penalty, this might move the string to a new line to keep it together rather than breaking it.
PenaltyBreakString: 10
```
In any case, I think you can close the issue!

**Comment by Wirena** [comment]
@chill-nemesis Keeping comments looks useful, thanks for this idea, i'll add it to my ToDo list
